services:
  db:
    image: postgres:15-alpine
    env_file:
      - ./backend/.env.${STAGE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      retries: 5
    networks: [gearup]

  # redis:
  #   image: redis:7-alpine
  #   networks: [gearup]

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
      target: ${STAGE:-dev}
    env_file:
      - ./backend/.env.${STAGE}
    depends_on:
      db:
        condition: service_healthy
      # redis:
      #   condition: service_started
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    networks: [gearup]

volumes:
  postgres_data:

networks:
  gearup:
