"""parent and parent_id fields added to Category model

Revision ID: 06caa029cd96
Revises: 27eecfc41435
Create Date: 2025-04-22 14:25:41.031276

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "06caa029cd96"
down_revision: Union[str, None] = "27eecfc41435"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("categories", sa.Column("parent_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "categories", "categories", ["parent_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "categories", type_="foreignkey")
    op.drop_column("categories", "parent_id")
    # ### end Alembic commands ###
